# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Pull request with Maven

on: [pull_request]

jobs:
  pr-build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            include:
                - os: ubuntu-latest
                  mvn: ./mvnw
                - os: windows-latest
                  mvn: mvn
                - os: macos-latest
                  mvn: ./mvnw
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: ${{ matrix.mvn }} -B verify
